### ISSUE TITLE
Feature request - parameter to change the default page title and h1 label

### ISSUE THREAD

**Issue by eveliseb** [phuongquan/daiquiri#3]
The default page title and h1 header is "daiquiri data quality report". We can change that directly in the HTML code after creation, but it would be nice to have a "title" parameter in the command. That way we could create multiple reports with custom titles based on the data or other environment variables.
Thanks!

**Comment by phuongquan** [comment]
Hi, thanks for the feedback, I'll add this to the list.

**Comment by eveliseb** [comment]
Merci!
